catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - '**/src'
  - theme

overrides:
  vite: 8.0.0-beta.0
patchedDependencies:
  cobe: patches/cobe.patch
  slidev-addon-graph: patches/slidev-addon-graph.patch
