catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - '**/src'
  - theme

patchedDependencies:
  slidev-addon-graph: patches/slidev-addon-graph.patch

ignoredBuiltDependencies:
  - '@tsparticles/engine'
  - esbuild
  - maplibre-gl
  - playwright-chromium
  - vue-demi
