catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - '**/src'
  - theme
overrides:
  vite: npm:rolldown-vite@latest
patchedDependencies:
  cobe: patches/cobe.patch
  slidev-addon-graph: patches/slidev-addon-graph.patch
