name: Trigger redeploy of linked websites

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  trigger-worker:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Trigger
        run: |
          curl -X POST https://redeploy.soubiran.dev/url \
            -H "Content-Type: application/json" \
            -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}" \
            -d '{
              "cloudflare": {
                "to_wait": {
                  "worker": "talks"
                },
                "to_redeploy": {
                  "worker": "soubiran-dev"
                }
              }
            }'
