name: Redeploy soubiran.dev

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  redeploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Trigger
        run: |
          curl -X POST https://redeploy.soubiran.dev/url \
            -H "Content-Type: application/json" \
            -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}" \
            -d '{
              "deploy_hook_url": "${{ secrets.CLOUDFLARE_SOUBIRAN_DEV_DEPLOY_HOOK_URL }}",
              "cloudflare": {
                "to_wait": {
                  "worker": "talks"
                },
              }
            }'
